// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uenblhorjgqvmqwdwcjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlbmJsaG9yamdxdm1xd2R3Y2p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwOTI4NDAsImV4cCI6MjA1MDY2ODg0MH0.zNdrJee57XjjuiAA57XuX7EgfRNQmBV0e2AoDVIvSxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);